### PR TITLE
Move ristretto benchmarks from ristretto to this repo

### PR DESCRIPTION
**Pull request by jarifibrahim**
See https://github.com/dgraph-io/ristretto/pull/40

This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/benchmarks/30)

### CODE REVIEW

**Comment by jarifibrahim** [comment]
I'm unable to sign the CLA. It gives me `Internal Server Error`.

**Comment by jarifibrahim** [comment]
Screenshot from 2019-09-06 17-30-35

**Comment by jarifibrahim** [comment]
@karlmcguire can you please look at this PR.

**Comment by mangalaman93** [comment]
@jarifibrahim this seems ready to merge.

**Pull request merged**
