### PR TITLE
Do mutations also as part of benchmarks

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/benchmarks/4)

### CODE REVIEW

**Comment by manishrjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[data/neo4j/query_test.go, line 68 at r1](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4#-KaioVJdi7DpGtSHFNUY:-KaioVJdi7DpGtSHFNUZ:b-ywsw8x) ([raw file](https://github.com/dgraph-io/benchmarks/blob/efe9c3c352b84d64d61ce27dff9bd7ea4239da7e/data/neo4j/query_test.go#L68)):*
> ```Go
> 	}
> 
> 	nq := graph.NQuad{
> ```

Move it down. Add a comment about this.

---

*[data/neo4j/query_test.go, line 71 at r1](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4#-KaiouFT557Ta2ZAVEEg:-KaiouFT557Ta2ZAVEEh:b9lcx31) ([raw file](https://github.com/dgraph-io/benchmarks/blob/efe9c3c352b84d64d61ce27dff9bd7ea4239da7e/data/neo4j/query_test.go#L71)):*
> ```Go
> 		Subject:     "m.0h_b6x1",
> 		Predicate:   "type.object.name.en",
> 		ObjectValue: &graph.Value{&graph.Value_StrVal{"Terminal"}},
> ```

Set the value randomly.

---

*[data/neo4j/query_test.go, line 91 at r1](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4#-KaioKk2htarnT-irpyc:-KaioKk2htarnT-irpyd:bwobbma) ([raw file](https://github.com/dgraph-io/benchmarks/blob/efe9c3c352b84d64d61ce27dff9bd7ea4239da7e/data/neo4j/query_test.go#L91)):*
> ```Go
> 					b.Fatalf("Error in getting response from server, %s", err)
> 				}
> 			}
> ```

b.StopTimer

---

*[data/neo4j/query_test.go, line 136 at r1](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4#-KaioZU1NGZ3NlKQ7dVd:-KaioZU1NGZ3NlKQ7dVe:bwobbma) ([raw file](https://github.com/dgraph-io/benchmarks/blob/efe9c3c352b84d64d61ce27dff9bd7ea4239da7e/data/neo4j/query_test.go#L136)):*
> ```Go
> 				}
> 			}
> 			conn.Close()
> ```

b.StopTimer

---

*[data/neo4j/query_test.go, line 157 at r1](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4#-KaipNt3Xrc-HY1kFOfU:-KaipNt3Xrc-HY1kFOfV:bubffsy) ([raw file](https://github.com/dgraph-io/benchmarks/blob/efe9c3c352b84d64d61ce27dff9bd7ea4239da7e/data/neo4j/query_test.go#L157)):*
> ```Go
> 						b.Fatal("Error in query", err)
> 					}
> 				}
> ```

Add a conn.close after this. Stop the timer before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4)*

**Comment by pawanrawal** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[data/neo4j/query_test.go, line 68 at r1](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4#-KaioVJdi7DpGtSHFNUY:-Kajc9RTqGEQfn0K-lLk:b-896fix) ([raw file](https://github.com/dgraph-io/benchmarks/blob/efe9c3c352b84d64d61ce27dff9bd7ea4239da7e/data/neo4j/query_test.go#L68)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Move it down. Add a comment about this.
</blockquote></details>

Done.

---

*[data/neo4j/query_test.go, line 71 at r1](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4#-KaiouFT557Ta2ZAVEEg:-KajcAOqBP-JFgKxN7tn:b-896fix) ([raw file](https://github.com/dgraph-io/benchmarks/blob/efe9c3c352b84d64d61ce27dff9bd7ea4239da7e/data/neo4j/query_test.go#L71)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Set the value randomly.
</blockquote></details>

Done.

---

*[data/neo4j/query_test.go, line 91 at r1](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4#-KaioKk2htarnT-irpyc:-KajcQjeQKuch1uLWua-:b-896fix) ([raw file](https://github.com/dgraph-io/benchmarks/blob/efe9c3c352b84d64d61ce27dff9bd7ea4239da7e/data/neo4j/query_test.go#L91)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

b.StopTimer
</blockquote></details>

Done.

---

*[data/neo4j/query_test.go, line 136 at r1](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4#-KaioZU1NGZ3NlKQ7dVd:-KajcX2brVudvUDIMRrL:b-896fix) ([raw file](https://github.com/dgraph-io/benchmarks/blob/efe9c3c352b84d64d61ce27dff9bd7ea4239da7e/data/neo4j/query_test.go#L136)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

b.StopTimer
</blockquote></details>

Done.

---

*[data/neo4j/query_test.go, line 157 at r1](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4#-KaipNt3Xrc-HY1kFOfU:-KajcbRwbRisQixqnmrh:b-gbvksq) ([raw file](https://github.com/dgraph-io/benchmarks/blob/efe9c3c352b84d64d61ce27dff9bd7ea4239da7e/data/neo4j/query_test.go#L157)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Add a conn.close after this. Stop the timer before.
</blockquote></details>

Can't stop timer in parallel, sending conn to pool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4)*

**Comment by manishrjain** [comment]
:lgtm: Just ensure that you stop timer for Neo4J as well.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4#-:-Kajkv67VQkzB2PrQ78c:b2hhj4n)*

**Comment by manishrjain** [comment]
Please close this.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/benchmarks/4#-:-KatYIPlT_dOsih6BI1i:b-jydkq1)*

**Pull request closed without merging**
