### PR TITLE
[Don't merge for now] Updating test files due New Type System.

### PR DESCRIPTION
**Pull request by MichelDiz**
Adding a type file that will be shared by 21 million test and 1 million.

PS. Still working on it.

## About the 1million.rdf itsefl

The structure is:

```
		# -------- directors --------
		# -------- End directors --------

		# -------- actors --------
		# -------- End actors --------

		# -------- genres --------
		# -------- End genres --------

		# -------- movies --------
		# -------- End movies --------

		# -------- Movies Types --------
		# -------- End of Movies Types --------

		# -------- Genres Types --------
		# -------- End Genres Types --------

		# -------- Actors Types* --------
		# -------- End Actors Types --------

		# -------- Directors Types --------
		# -------- End of Directors Types --------
```

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/benchmarks/23)

### CODE REVIEW

**Comment by campoy** [comment]
Hi there, @MichelDiz 

We need this ASAP as the release for 1.1 is coming up soon and we should be able to provide types on play.dgraph.io.

Could you provide an ETA?

**Comment by MichelDiz** [comment]
This schema type is working with most types. Tested with `expand(_all_)` and different queries, so the docs examples are covered. But need to review better. The 1 million and 21 million are also different need to check with Marting about this.

**Comment by campoy** [comment]
Thanks for the update, could you provide an estimated date for when you expect the task will be done?

**Comment by campoy** [comment]
Hey @martinmr and @MichelDiz,

Please figure out how to get this merged asap.

If it's ready for review, let's review it.
If it's not ready, please explain what is missing and when it will be ready.

**Comment by martinmr** [comment]
I need to modify the dataset so that the type predicates there match the type definitions Michel created. After that, we should be able to merge this.

I am working on this today.

**Comment by martinmr** [comment]
This is the full list of types from the 21 million dataset:

```
"actor"
"art_director"
"casting_director"
"character"
"cinematographer"
"collection"
"company"
"company_role_or_service"
"content_rating"
"content_rating_system"
"costumer_designer"
"crew_gig"
"crewmember"
"critic"
"cut"
"cut_type"
"director"
"distribution_medium"
"distributor"
"dubbing_performance"
"editor"
"featured_song"
"festival"
"festival_event"
"festival_focus"
"festival_sponsor"
"film"
"format"
"genre"
"job"
"location"
"music_contributor"
"performance"
"person_or_entity_appearing_in_film"
"personal_appearance"
"personal_appearance_type"
"producer"
"production_company"
"production_designer"
"regional_release_date"
"screening_venue"
"series"
"set_designer"
"song"
"song_performer"
"special_performance_type"
"story_contributor"
"subject"
"theorist"
"writer"
```

@MichelDiz  Which ones I should merge? All the ones for people I should merge into the Person type. Any other merging I should do?

**Comment by MichelDiz** [comment]
@martinmr I just did a small check and could be like this:

>All titles should be uppercase. All types are merged because they have equal predicates

> Also I should edit the 1 million dataset too.

```
====== Person =====
"actor"
"art_director"
"casting_director"
"costumer_designer"
"crewmember"
"critic"
"person_or_entity_appearing_in_film"
"production_designer"
"set_designer"
"writer"
"director"
"music_contributor"
"editor"
"producer"
"cinematographer"
"personal_appearance"
"song_performer"
"story_contributor"
"theorist"

===== Character ======
"character"
"collection" acho que esse é filme

===== Company =======
"company"
"company_role_or_service"
"distributor"
"production_company"
"festival_sponsor"

==== Not sure what type it could be ===

"content_rating"
"content_rating_system"

"crew_gig" - #This one seems to be lonely data, but it's about jobs positions.
"job" seems to be the same as crew_gig.
"special_performance_type" - This is also about Job type.

"cut" - #Also not sure what about this one, but seens to be a filme, cuz it has netflix id. So it could be "Movie".
"cut_type" - This is actually what type of media if was cut.

"distribution_medium" - This is the type of media it was distributed. Like DVD, Theater and so on.

------
"festival_focus" - This could be tha same name "festival_focus".

===== Personal_appearance_type ====
"personal_appearance_type"

===== Song ====
"featured_song"
"song"

===== Festival ====
"festival"

===== Event ====
"screening_venue"
"festival_event"

===== Movie ====
"film"
"dubbing_performance"
"regional_release_date"

===== Format ====
"format"

===== Genre ====
"genre"

===== Location ====
"location"

===== Performance ====
"performance"

===== Series ====
"series"

===== Subject ====
"subject"
```

**Comment by martinmr** [comment]
Thanks a lot, I'll work on this now. I think we can leave the ones you are unsure of as-is (maybe change the name to use uppercase). They seem pretty niche predicates so I doubt they will cause any documentation query to break if the definition is missing.

**Comment by martinmr** [comment]
I have the script to convert the datasets to the new types (works for both the 1 million and 21 million dataset). I have to go so I'll send the PR tomorrow.

**Comment by MichelDiz** [comment]
> Are you testing this by doing two separate Alter calls? one with the preds and another one with the types?
yes, are u okay with that? shall we enforce the use of one single schema file? I think it would get bigger and bigger. Maybe we could support the add multiple schemas in the -s flag.

> Also, I'd get rid of the square brackets in the file name. Something like million-types.schema.
sure

**Comment by martinmr** [comment]
@MichelDiz I think this is good to merge so feel free to do it.

**Pull request merged**
